name: ${NAME}
version: ${VERSION}
main: ${PACKAGE}.ServerManagerPlugin
description: ${DESCRIPTION}
api-version: ${MCVERSION}
loader: ${PACKAGE}.ServerManagerLoader
authors: ["winlogon"]
folia-supported: true
