[versions]
shadow = "9.3.0"
paper-api = "1.21.11-R0.1-SNAPSHOT"
jresult = "2.0.0"
configlib-paper = "4.6.3"
oshi-core = "6.4.0"
quartz = "2.3.2"
lombok = "1.18.42"
adventure-api = "4.25.0"
junit = "6.0.1"
asynccraftr = "0.2.0"
jackson-jq = "1.6.1"

[libraries]
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper-api" }
jresult = { group = "org.winlogon", name = "jresult", version.ref = "jresult" }
configlib-paper = { group = "de.exlll", name = "configlib-paper", version.ref = "configlib-paper" }
oshi-core = { group = "com.github.oshi", name = "oshi-core", version.ref = "oshi-core" }
quartz = { group = "org.quartz-scheduler", name = "quartz", version.ref = "quartz" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }
asynccraftr = { group = "org.winlogon", name = "asynccraftr", version.ref = "asynccraftr" }
jackson-jq = { group = "net.thisptr", name = "jackson-jq", version.ref = "jackson-jq" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
